# Generated by Django 5.2.8 on 2025-11-27 19:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de categoría')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría de Material',
                'verbose_name_plural': 'Categorías de Materiales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del material')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del material')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('stock_actual', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock actual')),
                ('stock_minimo', models.IntegerField(default=0, help_text='Cantidad mínima antes de alertar', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock mínimo')),
                ('unidad_medida', models.CharField(default='unidad', help_text='Ej: unidad, metro, kg, etc.', max_length=20, verbose_name='Unidad de medida')),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de compra')),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de venta')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('bajo_stock', 'Bajo Stock'), ('agotado', 'Agotado'), ('descontinuado', 'Descontinuado')], default='disponible', max_length=20, verbose_name='Estado')),
                ('ubicacion', models.CharField(blank=True, max_length=200, verbose_name='Ubicación en almacén')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='inventario.categoriamaterial', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('devolucion', 'Devolución')], max_length=20, verbose_name='Tipo de movimiento')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['codigo'], name='inventario__codigo_f491e8_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['categoria', 'estado'], name='inventario__categor_dc0c76_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['stock_actual'], name='inventario__stock_a_facdcc_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['material', 'fecha'], name='inventario__materia_b5d7ab_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo'], name='inventario__tipo_b85d84_idx'),
        ),
    ]
