# Generated by Django 5.2.8 on 2025-12-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unidad_medida',
            field=models.CharField(choices=[('pza', 'Pieza (Pza)'), ('caja', 'Caja'), ('paquete', 'Paquete'), ('rollo', 'Rollo'), ('metro', 'Metro (m)'), ('kg', 'Kilogramo (Kg)'), ('litro', 'Litro (L)'), ('par', 'Par'), ('juego', 'Juego'), ('bolsa', 'Bolsa'), ('bobina', 'Bobina'), ('carrete', 'Carrete'), ('unidad', 'Unidad'), ('docena', 'Docena'), ('millar', 'Millar'), ('otro', 'Otro')], default='pza', max_length=20, verbose_name='Unidad de medida'),
        ),
    ]
