# Generated by Django 5.2.8 on 2025-11-27 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('plantilla', models.TextField(blank=True, verbose_name='Plantilla de mensaje')),
            ],
            options={
                'verbose_name': 'Tipo de Notificación',
                'verbose_name_plural': 'Tipos de Notificación',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('dias_antes_vencimiento', models.IntegerField(default=3, help_text='Días antes del vencimiento para enviar notificación', verbose_name='Días antes del vencimiento')),
                ('dias_despues_vencimiento', models.IntegerField(default=1, help_text='Días después del vencimiento para enviar recordatorio', verbose_name='Días después del vencimiento')),
                ('canal_preferido', models.CharField(choices=[('email', 'Correo electrónico'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('sistema', 'Sistema')], default='email', max_length=20, verbose_name='Canal preferido')),
                ('tipo_notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='notificaciones.tiponotificacion', verbose_name='Tipo de notificación')),
            ],
            options={
                'verbose_name': 'Configuración de Notificación',
                'verbose_name_plural': 'Configuraciones de Notificación',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('canal', models.CharField(choices=[('email', 'Correo electrónico'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('sistema', 'Sistema')], default='email', max_length=20, verbose_name='Canal de envío')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('fallida', 'Fallida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_programada', models.DateTimeField(blank=True, help_text='Fecha en que se debe enviar la notificación', null=True, verbose_name='Fecha programada')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('resultado', models.TextField(blank=True, help_text='Información sobre el resultado del envío', null=True, verbose_name='Resultado')),
                ('intentos', models.IntegerField(default=0, verbose_name='Intentos de envío')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='clientes.cliente', verbose_name='Cliente')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='pagos.pago', verbose_name='Pago relacionado')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notificaciones.tiponotificacion', verbose_name='Tipo de notificación')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['cliente', 'estado'], name='notificacio_cliente_4f0143_idx'), models.Index(fields=['fecha_programada'], name='notificacio_fecha_p_42e0e6_idx'), models.Index(fields=['tipo', 'canal'], name='notificacio_tipo_id_e8b002_idx')],
            },
        ),
    ]
