# Generated by Django 5.2.8 on 2026-01-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='canales_adicionales',
            field=models.JSONField(blank=True, default=list, help_text='Canales adicionales para envío (email, sms, whatsapp, sistema)', verbose_name='Canales adicionales'),
        ),
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='dias_semana',
            field=models.JSONField(blank=True, default=list, help_text='Días de la semana para envío (0=Lunes, 6=Domingo)', verbose_name='Días de la semana'),
        ),
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='frecuencia',
            field=models.CharField(choices=[('una_vez', 'Una vez'), ('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('personalizado', 'Personalizado')], default='una_vez', max_length=20, verbose_name='Frecuencia'),
        ),
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='hora_envio',
            field=models.TimeField(default='09:00', help_text='Hora del día para enviar notificaciones', verbose_name='Hora de envío'),
        ),
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='intervalo_reintentos',
            field=models.IntegerField(default=24, help_text='Horas entre reintentos si falla el envío', verbose_name='Intervalo de reintentos (horas)'),
        ),
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='max_intentos',
            field=models.IntegerField(default=3, help_text='Número máximo de intentos de envío', verbose_name='Máximo de intentos'),
        ),
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='monto_minimo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enviar solo si el monto es mayor o igual a este valor', max_digits=10, verbose_name='Monto mínimo'),
        ),
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='plantilla_personalizada',
            field=models.TextField(blank=True, help_text='Plantilla personalizada (sobrescribe la del tipo de notificación)', verbose_name='Plantilla personalizada'),
        ),
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='recordatorios_escalonados',
            field=models.JSONField(blank=True, default=list, help_text='Lista de días para recordatorios adicionales (ej: [7, 3, 1, 0, -1, -3])', verbose_name='Recordatorios escalonados'),
        ),
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='solo_activos',
            field=models.BooleanField(default=True, help_text='Enviar solo a clientes con estado activo', verbose_name='Solo clientes activos'),
        ),
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='solo_vencidos',
            field=models.BooleanField(default=False, help_text='Enviar solo si el pago está vencido', verbose_name='Solo vencidos'),
        ),
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización'),
        ),
    ]
