# Generated by Django 5.2.8 on 2026-01-19 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_mejorar_configuracion_notificaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionnotificacion',
            name='canales_adicionales',
        ),
        migrations.RemoveField(
            model_name='configuracionnotificacion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='configuracionnotificacion',
            name='dias_semana',
        ),
        migrations.RemoveField(
            model_name='configuracionnotificacion',
            name='frecuencia',
        ),
        migrations.RemoveField(
            model_name='configuracionnotificacion',
            name='hora_envio',
        ),
        migrations.RemoveField(
            model_name='configuracionnotificacion',
            name='intervalo_reintentos',
        ),
        migrations.RemoveField(
            model_name='configuracionnotificacion',
            name='max_intentos',
        ),
        migrations.RemoveField(
            model_name='configuracionnotificacion',
            name='monto_minimo',
        ),
        migrations.RemoveField(
            model_name='configuracionnotificacion',
            name='plantilla_personalizada',
        ),
        migrations.RemoveField(
            model_name='configuracionnotificacion',
            name='recordatorios_escalonados',
        ),
        migrations.RemoveField(
            model_name='configuracionnotificacion',
            name='solo_activos',
        ),
        migrations.RemoveField(
            model_name='configuracionnotificacion',
            name='solo_vencidos',
        ),
        migrations.RemoveField(
            model_name='configuracionnotificacion',
            name='updated_at',
        ),
    ]
