# Generated by Django 5.2.8 on 2025-11-27 19:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('instalaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_mensual', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto mensual')),
                ('dia_vencimiento', models.IntegerField(help_text='Día del mes en que vence el pago (1-31)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Día de vencimiento')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('instalacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_pago', to='instalaciones.instalacion', verbose_name='Instalación')),
            ],
            options={
                'verbose_name': 'Plan de Pago',
                'verbose_name_plural': 'Planes de Pago',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto')),
                ('periodo_mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='Mes')),
                ('periodo_anio', models.IntegerField(verbose_name='Año')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de crédito/débito'), ('deposito', 'Depósito'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Método de pago')),
                ('referencia_pago', models.CharField(blank=True, help_text='Número de transacción, referencia bancaria, etc.', max_length=100, null=True, verbose_name='Referencia de pago')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='clientes.cliente', verbose_name='Cliente')),
                ('instalacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='instalaciones.instalacion', verbose_name='Instalación')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_vencimiento', '-fecha_registro'],
                'indexes': [models.Index(fields=['cliente', 'estado'], name='pagos_pago_cliente_01e94c_idx'), models.Index(fields=['fecha_vencimiento'], name='pagos_pago_fecha_v_9d409c_idx'), models.Index(fields=['periodo_anio', 'periodo_mes'], name='pagos_pago_periodo_754296_idx')],
            },
        ),
    ]
