# Generated by Django 5.2.8 on 2025-12-30 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='periodo_anio',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='planpago',
            name='dia_vencimiento',
            field=models.IntegerField(help_text='Día del mes en que vence el pago (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Día de vencimiento'),
        ),
    ]
