# Generated by Django 5.2.8 on 2026-01-02 23:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_cambiar_periodo_mes_a_nombres'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasarela', models.CharField(choices=[('stripe', 'Stripe'), ('mercadopago', 'Mercado Pago'), ('paypal', 'PayPal'), ('conekta', 'Conekta')], default='stripe', max_length=20, verbose_name='Pasarela de pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completada', 'Completada'), ('fallida', 'Fallida'), ('cancelada', 'Cancelada'), ('reembolsada', 'Reembolsada')], default='pendiente', max_length=20, verbose_name='Estado de la transacción')),
                ('id_transaccion_pasarela', models.CharField(help_text='ID único de la transacción en la pasarela de pago', max_length=200, unique=True, verbose_name='ID de transacción (pasarela)')),
                ('id_pago_intento', models.CharField(blank=True, help_text='ID del intento de pago en la pasarela', max_length=200, null=True, verbose_name='ID de intento de pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto de la transacción')),
                ('moneda', models.CharField(default='MXN', help_text='Código de moneda ISO 4217 (MXN, USD, etc.)', max_length=3, verbose_name='Moneda')),
                ('metodo_pago_tipo', models.CharField(blank=True, help_text='card, bank_transfer, etc.', max_length=50, null=True, verbose_name='Tipo de método de pago')),
                ('ultimos_digitos', models.CharField(blank=True, help_text='Últimos 4 dígitos de la tarjeta (si aplica)', max_length=4, null=True, verbose_name='Últimos 4 dígitos')),
                ('datos_respuesta', models.JSONField(blank=True, default=dict, help_text='Respuesta completa de la pasarela en formato JSON', verbose_name='Datos de respuesta')),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error si la transacción falló', null=True, verbose_name='Mensaje de error')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('fecha_completada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completación')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='pagos.pago', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Transacción de Pago',
                'verbose_name_plural': 'Transacciones de Pago',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['pago', 'estado'], name='pagos_trans_pago_id_e05192_idx'), models.Index(fields=['id_transaccion_pasarela'], name='pagos_trans_id_tran_0674de_idx'), models.Index(fields=['fecha_creacion'], name='pagos_trans_fecha_c_7a1c4f_idx')],
            },
        ),
    ]
