# Generated by Django 5.2.8 on 2026-01-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_remove_cliente_unique_email_when_not_null_and_more'),
        ('instalaciones', '0008_cambioestadoinstalacion_historicalinstalacion_and_more'),
        ('pagos', '0004_transaccionpago'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['pendiente', 'pagado', 'vencido'])), fields=('cliente', 'instalacion', 'periodo_mes', 'periodo_anio'), name='unique_periodo_por_cliente_instalacion_activo'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['pendiente', 'pagado', 'vencido']), ('instalacion__isnull', True)), fields=('cliente', 'periodo_mes', 'periodo_anio'), name='unique_periodo_por_cliente_sin_instalacion_activo'),
        ),
    ]
