# Generated by Django 5.2.8 on 2026-01-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_pago_unique_periodo_por_cliente_instalacion_activo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pago',
            name='unique_periodo_por_cliente_instalacion_activo',
        ),
        migrations.RemoveConstraint(
            model_name='pago',
            name='unique_periodo_por_cliente_sin_instalacion_activo',
        ),
    ]
