# Generated by Django 5.2.8 on 2026-01-02 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True, verbose_name='Configuración activa')),
                ('nombre_empresa', models.CharField(default='AdminiRed', help_text='Nombre que aparecerá en el header y footer', max_length=100, verbose_name='Nombre de la empresa')),
                ('logo', models.ImageField(blank=True, help_text='Imagen del logo (recomendado: PNG transparente, máximo 200x60px)', null=True, upload_to='configuracion/', verbose_name='Logo de la empresa')),
                ('color_primario', models.CharField(default='#667eea', help_text='Color principal del sistema (header, botones principales)', max_length=7, validators=[django.core.validators.RegexValidator(message='Formato de color inválido. Use formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color primario')),
                ('color_secundario', models.CharField(default='#764ba2', help_text='Color secundario (gradientes, acentos)', max_length=7, validators=[django.core.validators.RegexValidator(message='Formato de color inválido. Use formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color secundario')),
                ('color_exito', models.CharField(default='#10b981', help_text='Color para acciones exitosas, badges de éxito', max_length=7, validators=[django.core.validators.RegexValidator(message='Formato de color inválido. Use formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color de éxito')),
                ('color_advertencia', models.CharField(default='#f59e0b', help_text='Color para advertencias, badges de advertencia', max_length=7, validators=[django.core.validators.RegexValidator(message='Formato de color inválido. Use formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color de advertencia')),
                ('color_peligro', models.CharField(default='#ef4444', help_text='Color para errores, badges de peligro', max_length=7, validators=[django.core.validators.RegexValidator(message='Formato de color inválido. Use formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color de peligro')),
                ('color_info', models.CharField(default='#3b82f6', help_text='Color para información, badges de info', max_length=7, validators=[django.core.validators.RegexValidator(message='Formato de color inválido. Use formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color de información')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
    ]
