# Generated by Django 5.2.8 on 2026-01-13 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracionsistema_descripcion_sistema_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('cliente', 'Cliente'), ('administrador', 'Administrador'), ('supervisor', 'Supervisor'), ('instalador', 'Instalador'), ('tecnico', 'Técnico'), ('otro', 'Otro')], default='otro', help_text='Tipo general de usuario (puede ser más específico con roles)', max_length=20, verbose_name='Tipo de usuario')),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=15, null=True, verbose_name='Teléfono')),
                ('foto', models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='perfiles/', verbose_name='Foto de perfil')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el usuario', null=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'ordering': ['usuario__username'],
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del permiso (ej: Ver clientes, Editar pagos)', max_length=100, unique=True, verbose_name='Nombre del permiso')),
                ('codigo', models.CharField(help_text='Código único para referencia programática (ej: ver_clientes, editar_pagos). Solo letras, números y guiones bajos.', max_length=100, unique=True, verbose_name='Código del permiso')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del permiso', null=True, verbose_name='Descripción')),
                ('categoria', models.CharField(db_index=True, help_text='Categoría del permiso para agruparlos (ej: clientes, pagos, instalaciones)', max_length=50, verbose_name='Categoría')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el permiso está activo', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'ordering': ['categoria', 'nombre'],
                'indexes': [models.Index(fields=['codigo', 'activo'], name='core_permis_codigo_b36d27_idx'), models.Index(fields=['categoria', 'activo'], name='core_permis_categor_284616_idx')],
            },
        ),
        migrations.CreateModel(
            name='PermisoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permiso_roles', to='core.permiso', verbose_name='Permiso')),
            ],
            options={
                'verbose_name': 'Permiso de Rol',
                'verbose_name_plural': 'Permisos de Roles',
                'ordering': ['rol', 'permiso'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único del rol (ej: Administrador, Supervisor, Instalador)', max_length=100, unique=True, verbose_name='Nombre del rol')),
                ('codigo', models.CharField(help_text='Código único para referencia programática (ej: admin, supervisor, instalador). Solo letras, números y guiones bajos.', max_length=50, unique=True, verbose_name='Código del rol')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del rol y sus responsabilidades', null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el rol está activo y puede ser asignado a usuarios', verbose_name='Activo')),
                ('es_sistema', models.BooleanField(default=False, help_text='Si está marcado, es un rol especial del sistema y no puede ser eliminado', verbose_name='Es rol de sistema')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('permisos', models.ManyToManyField(blank=True, related_name='roles', through='core.PermisoRol', to='core.permiso', verbose_name='Permisos')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='permisorol',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permiso_roles', to='core.rol', verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el rol está activo para este usuario', verbose_name='Activo')),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_roles', to='core.rol', verbose_name='Rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_roles', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuario',
                'ordering': ['usuario', 'rol'],
            },
        ),
        migrations.AddIndex(
            model_name='rol',
            index=models.Index(fields=['codigo', 'activo'], name='core_rol_codigo_28b50e_idx'),
        ),
        migrations.AddIndex(
            model_name='rol',
            index=models.Index(fields=['activo'], name='core_rol_activo_340e74_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='permisorol',
            unique_together={('rol', 'permiso')},
        ),
        migrations.AddIndex(
            model_name='usuariorol',
            index=models.Index(fields=['usuario', 'activo'], name='core_usuari_usuario_9064c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usuariorol',
            unique_together={('usuario', 'rol')},
        ),
    ]
