# Generated by Django 5.2.8 on 2026-01-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agregar_sistema_roles_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='imagen_hero',
            field=models.ImageField(blank=True, help_text='Imagen de fondo para la sección hero en la página de inicio (recomendado: 1920x400px o similar)', null=True, upload_to='configuracion/', verbose_name='Imagen del Hero (Página de Inicio)'),
        ),
    ]
