# Generated by Django 5.2.8 on 2026-01-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hacer_descripcion_sistema_opcional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='imagen_hero',
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='descripcion_sistema',
            field=models.CharField(default='Sistema para el control total de instalaciones de internet', help_text='Descripción corta que aparecerá como subtítulo en el home y footer', max_length=200, verbose_name='Descripción del sistema'),
        ),
    ]
