# Generated by Django 5.2.8 on 2026-01-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_configuracionsistema_imagen_hero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='pagos_online_habilitados',
            field=models.BooleanField(default=True, help_text='Si está desactivado, los clientes no podrán pagar en línea. Los administradores podrán registrar pagos manuales.', verbose_name='Pagos en línea habilitados'),
        ),
    ]
