# Generated by Django 5.2.8 on 2026-01-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_configuracionsistema_pagos_online_habilitados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='pagos_online_habilitados',
        ),
    ]
