# Generated by Django 5.2.8 on 2025-11-27 19:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInstalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Tipo de instalación')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Instalación',
                'verbose_name_plural': 'Tipos de Instalación',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_instalacion', models.TextField(verbose_name='Dirección de instalación')),
                ('coordenadas', models.CharField(blank=True, help_text='Formato: latitud,longitud', max_length=100, null=True, verbose_name='Coordenadas (lat, lng)')),
                ('plan_nombre', models.CharField(max_length=100, verbose_name='Nombre del plan')),
                ('velocidad_descarga', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Velocidad de descarga (Mbps)')),
                ('velocidad_subida', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Velocidad de subida (Mbps)')),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio mensual')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('programada', 'Programada'), ('en_proceso', 'En Proceso'), ('activa', 'Activa'), ('suspendida', 'Suspendida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('fecha_programada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha programada')),
                ('fecha_instalacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de instalación')),
                ('fecha_activacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de activación')),
                ('ip_asignada', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP asignada')),
                ('mac_equipo', models.CharField(blank=True, max_length=17, null=True, verbose_name='MAC del equipo')),
                ('numero_contrato', models.CharField(max_length=50, unique=True, verbose_name='Número de contrato')),
                ('notas_instalacion', models.TextField(blank=True, null=True, verbose_name='Notas de instalación')),
                ('notas_tecnicas', models.TextField(blank=True, null=True, verbose_name='Notas técnicas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalaciones', to='clientes.cliente', verbose_name='Cliente')),
                ('tipo_instalacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instalaciones.tipoinstalacion', verbose_name='Tipo de instalación')),
            ],
            options={
                'verbose_name': 'Instalación',
                'verbose_name_plural': 'Instalaciones',
                'ordering': ['-fecha_solicitud'],
                'indexes': [models.Index(fields=['cliente', 'estado'], name='instalacion_cliente_f08030_idx'), models.Index(fields=['numero_contrato'], name='instalacion_numero__f65ac4_idx'), models.Index(fields=['fecha_programada'], name='instalacion_fecha_p_d5e659_idx')],
            },
        ),
    ]
