# Generated by Django 5.2.8 on 2025-12-01 22:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanInternet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del plan')),
                ('velocidad_descarga', models.IntegerField(help_text='Velocidad de descarga en Mbps', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Velocidad de descarga (Mbps)')),
                ('velocidad_subida', models.IntegerField(blank=True, help_text='Velocidad de subida en Mbps (opcional)', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Velocidad de subida (Mbps)')),
                ('precio_mensual', models.DecimalField(decimal_places=2, help_text='Precio mensual del plan', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio mensual')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el plan está disponible', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Plan de Internet',
                'verbose_name_plural': 'Planes de Internet',
                'ordering': ['precio_mensual', 'velocidad_descarga'],
            },
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='plan_nombre',
            field=models.CharField(help_text='Nombre personalizado del plan (si no se selecciona del catálogo)', max_length=100, verbose_name='Nombre del plan'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='precio_mensual',
            field=models.DecimalField(decimal_places=2, help_text='Se llena automáticamente si se selecciona un plan del catálogo', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio mensual'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='velocidad_descarga',
            field=models.IntegerField(help_text='Se llena automáticamente si se selecciona un plan del catálogo', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Velocidad de descarga (Mbps)'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='velocidad_subida',
            field=models.IntegerField(blank=True, help_text='Se llena automáticamente si se selecciona un plan del catálogo', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Velocidad de subida (Mbps)'),
        ),
        migrations.AddField(
            model_name='instalacion',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Plan del catálogo (opcional, puede especificar manualmente)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instalaciones', to='instalaciones.planinternet', verbose_name='Plan de Internet'),
        ),
    ]
