# Generated by Django 5.2.8 on 2025-12-31 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0002_planinternet_alter_instalacion_plan_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNumeroContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True, verbose_name='Configuración activa')),
                ('formato', models.CharField(default='INST-{YYYY}{MM}{DD}-{####}', help_text='Variables disponibles: {YYYY} (año), {YY} (año 2 dígitos), {MM} (mes), {DD} (día), {####} (número secuencial), {PREFIJO} (prefijo personalizado)', max_length=200, verbose_name='Formato del número de contrato')),
                ('prefijo', models.CharField(blank=True, default='INST', help_text='Prefijo opcional (se usa con {PREFIJO})', max_length=20, verbose_name='Prefijo personalizado')),
                ('numero_inicial', models.IntegerField(default=1, help_text='Número inicial para la secuencia (ej: 1, 100, 1000)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número inicial')),
                ('digitos_secuencia', models.IntegerField(default=4, help_text='Cantidad de dígitos para el número secuencial (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(10)], verbose_name='Dígitos de secuencia')),
                ('reiniciar_diario', models.BooleanField(default=True, help_text='Si está activo, la secuencia se reinicia cada día', verbose_name='Reiniciar secuencia diariamente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Número de Contrato',
                'verbose_name_plural': 'Configuraciones de Número de Contrato',
            },
        ),
    ]
