# Generated by Django 5.2.8 on 2025-12-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0004_alter_instalacion_numero_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacion',
            name='numero_contrato',
            field=models.CharField(blank=True, default='', help_text='Se generará automáticamente si se deja vacío', max_length=50, unique=True, verbose_name='Número de contrato'),
        ),
    ]
