# Generated by Django 5.2.8 on 2026-01-02 18:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0005_alter_instalacion_numero_contrato'),
        ('inventario', '0002_add_unidad_medida_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialInstalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(help_text='Cantidad necesaria del material', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el uso de este material', null=True, verbose_name='Notas')),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='instalaciones.instalacion', verbose_name='Instalación')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalaciones', to='inventario.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Material de Instalación',
                'verbose_name_plural': 'Materiales de Instalación',
                'ordering': ['material__nombre'],
                'unique_together': {('instalacion', 'material')},
            },
        ),
    ]
