# Generated by Django 5.2.8 on 2026-01-02 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0006_materialinstalacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionnumerocontrato',
            name='digitos_secuencia',
        ),
        migrations.RemoveField(
            model_name='configuracionnumerocontrato',
            name='formato',
        ),
        migrations.RemoveField(
            model_name='configuracionnumerocontrato',
            name='numero_inicial',
        ),
        migrations.RemoveField(
            model_name='configuracionnumerocontrato',
            name='reiniciar_diario',
        ),
        migrations.AddField(
            model_name='configuracionnumerocontrato',
            name='formato_anio',
            field=models.CharField(choices=[('completo', 'Completo (YYYY)'), ('corto', 'Corto (YY)')], default='completo', max_length=10, verbose_name='Formato del año'),
        ),
        migrations.AddField(
            model_name='configuracionnumerocontrato',
            name='incluir_anio',
            field=models.BooleanField(default=True, help_text='Incluir el año en el número de contrato', verbose_name='Incluir año'),
        ),
        migrations.AddField(
            model_name='configuracionnumerocontrato',
            name='incluir_mes',
            field=models.BooleanField(default=True, help_text='Incluir el mes en el número de contrato', verbose_name='Incluir mes'),
        ),
        migrations.AddField(
            model_name='configuracionnumerocontrato',
            name='incluir_secuencia',
            field=models.BooleanField(default=True, help_text='Incluir número secuencial', verbose_name='Incluir secuencia'),
        ),
        migrations.AddField(
            model_name='configuracionnumerocontrato',
            name='longitud_secuencia',
            field=models.IntegerField(default=4, help_text='Cantidad de dígitos para el número secuencial', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Longitud de secuencia'),
        ),
        migrations.AddField(
            model_name='configuracionnumerocontrato',
            name='resetear_secuencia',
            field=models.CharField(choices=[('nunca', 'Nunca (secuencia continua)'), ('mensual', 'Mensual'), ('anual', 'Anual')], default='mensual', help_text='Cuándo se reinicia la secuencia numérica', max_length=10, verbose_name='Resetear secuencia'),
        ),
        migrations.AddField(
            model_name='configuracionnumerocontrato',
            name='separador',
            field=models.CharField(default='-', help_text='Carácter separador entre partes (ej: -, _, /)', max_length=5, verbose_name='Separador'),
        ),
        migrations.AddField(
            model_name='configuracionnumerocontrato',
            name='sufijo',
            field=models.CharField(blank=True, help_text='Sufijo opcional del número de contrato', max_length=20, verbose_name='Sufijo'),
        ),
        migrations.AlterField(
            model_name='configuracionnumerocontrato',
            name='activa',
            field=models.BooleanField(default=True, help_text='Solo una configuración puede estar activa', verbose_name='Configuración activa'),
        ),
        migrations.AlterField(
            model_name='configuracionnumerocontrato',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='configuracionnumerocontrato',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='configuracionnumerocontrato',
            name='prefijo',
            field=models.CharField(blank=True, default='CONT', help_text='Prefijo del número de contrato (ej: CONT, INST)', max_length=20, verbose_name='Prefijo'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='numero_contrato',
            field=models.CharField(blank=True, help_text='Se genera automáticamente si se deja vacío', max_length=50, null=True, unique=True, verbose_name='Número de contrato'),
        ),
    ]
