# Generated by Django 5.2.8 on 2026-01-05 18:04

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_remove_cliente_unique_email_when_not_null_and_more'),
        ('instalaciones', '0007_remove_configuracionnumerocontrato_digitos_secuencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioEstadoInstalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('pendiente', 'Pendiente'), ('programada', 'Programada'), ('en_proceso', 'En Proceso'), ('activa', 'Activa'), ('suspendida', 'Suspendida'), ('cancelada', 'Cancelada')], max_length=20, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(choices=[('pendiente', 'Pendiente'), ('programada', 'Programada'), ('en_proceso', 'En Proceso'), ('activa', 'Activa'), ('suspendida', 'Suspendida'), ('cancelada', 'Cancelada')], max_length=20, verbose_name='Estado nuevo')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cambio')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el cambio de estado', null=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Cambio de Estado',
                'verbose_name_plural': 'Cambios de Estado',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalInstalacion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('direccion_instalacion', models.TextField(verbose_name='Dirección de instalación')),
                ('coordenadas', models.CharField(blank=True, help_text='Formato: latitud,longitud', max_length=100, null=True, verbose_name='Coordenadas (lat, lng)')),
                ('plan_nombre', models.CharField(help_text='Nombre personalizado del plan (si no se selecciona del catálogo)', max_length=100, verbose_name='Nombre del plan')),
                ('velocidad_descarga', models.IntegerField(help_text='Se llena automáticamente si se selecciona un plan del catálogo', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Velocidad de descarga (Mbps)')),
                ('velocidad_subida', models.IntegerField(blank=True, help_text='Se llena automáticamente si se selecciona un plan del catálogo', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Velocidad de subida (Mbps)')),
                ('precio_mensual', models.DecimalField(decimal_places=2, help_text='Se llena automáticamente si se selecciona un plan del catálogo', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio mensual')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('programada', 'Programada'), ('en_proceso', 'En Proceso'), ('activa', 'Activa'), ('suspendida', 'Suspendida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de solicitud')),
                ('fecha_programada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha programada')),
                ('fecha_instalacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de instalación')),
                ('fecha_activacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de activación')),
                ('ip_asignada', models.GenericIPAddressField(blank=True, help_text='La IP debe ser única en el sistema', null=True, verbose_name='IP asignada')),
                ('mac_equipo', models.CharField(blank=True, help_text='La MAC debe ser única en el sistema', max_length=17, null=True, verbose_name='MAC del equipo')),
                ('numero_contrato', models.CharField(blank=True, db_index=True, help_text='Se genera automáticamente si se deja vacío', max_length=50, null=True, verbose_name='Número de contrato')),
                ('notas_instalacion', models.TextField(blank=True, null=True, verbose_name='Notas de instalación')),
                ('notas_tecnicas', models.TextField(blank=True, null=True, verbose_name='Notas técnicas')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Instalación',
                'verbose_name_plural': 'historical Instalaciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='ip_asignada',
            field=models.GenericIPAddressField(blank=True, help_text='La IP debe ser única en el sistema', null=True, verbose_name='IP asignada'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='mac_equipo',
            field=models.CharField(blank=True, help_text='La MAC debe ser única en el sistema', max_length=17, null=True, verbose_name='MAC del equipo'),
        ),
        migrations.AddIndex(
            model_name='instalacion',
            index=models.Index(fields=['ip_asignada'], name='instalacion_ip_asig_d6c966_idx'),
        ),
        migrations.AddIndex(
            model_name='instalacion',
            index=models.Index(fields=['mac_equipo'], name='instalacion_mac_equ_f6a74a_idx'),
        ),
        migrations.AddConstraint(
            model_name='instalacion',
            constraint=models.UniqueConstraint(condition=models.Q(('ip_asignada__isnull', False)), fields=('ip_asignada',), name='unique_ip_when_not_null'),
        ),
        migrations.AddConstraint(
            model_name='instalacion',
            constraint=models.UniqueConstraint(condition=models.Q(('mac_equipo__isnull', False)), fields=('mac_equipo',), name='unique_mac_when_not_null'),
        ),
        migrations.AddField(
            model_name='cambioestadoinstalacion',
            name='instalacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado', to='instalaciones.instalacion', verbose_name='Instalación'),
        ),
        migrations.AddField(
            model_name='cambioestadoinstalacion',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó el cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='historicalinstalacion',
            name='cliente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='historicalinstalacion',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinstalacion',
            name='plan',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Plan del catálogo (opcional, puede especificar manualmente)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instalaciones.planinternet', verbose_name='Plan de Internet'),
        ),
        migrations.AddField(
            model_name='historicalinstalacion',
            name='tipo_instalacion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='instalaciones.tipoinstalacion', verbose_name='Tipo de instalación'),
        ),
        migrations.AddIndex(
            model_name='cambioestadoinstalacion',
            index=models.Index(fields=['instalacion', 'fecha_cambio'], name='instalacion_instala_e27e05_idx'),
        ),
    ]
