# Generated by Django 5.2.8 on 2026-01-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0008_cambioestadoinstalacion_historicalinstalacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambioestadoinstalacion',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('programada', 'Programada'), ('en_proceso', 'En Proceso'), ('activa', 'Activa'), ('suspendida', 'Suspendida'), ('cancelada', 'Cancelada')], help_text='Estado anterior (null para instalaciones nuevas)', max_length=20, null=True, verbose_name='Estado anterior'),
        ),
    ]
