# Generated by Django 5.2.8 on 2026-01-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0009_allow_null_estado_anterior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinstalacion',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='historicalinstalacion',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalinstalacion',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='historicalinstalacion',
            name='tipo_instalacion',
        ),
        migrations.RemoveConstraint(
            model_name='instalacion',
            name='unique_ip_when_not_null',
        ),
        migrations.RemoveConstraint(
            model_name='instalacion',
            name='unique_mac_when_not_null',
        ),
        migrations.RemoveIndex(
            model_name='instalacion',
            name='instalacion_ip_asig_d6c966_idx',
        ),
        migrations.RemoveIndex(
            model_name='instalacion',
            name='instalacion_mac_equ_f6a74a_idx',
        ),
        migrations.AlterField(
            model_name='cambioestadoinstalacion',
            name='estado_anterior',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('programada', 'Programada'), ('en_proceso', 'En Proceso'), ('activa', 'Activa'), ('suspendida', 'Suspendida'), ('cancelada', 'Cancelada')], default=1, max_length=20, verbose_name='Estado anterior'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='ip_asignada',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP asignada'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='mac_equipo',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='MAC del equipo'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='numero_contrato',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Número de contrato'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HistoricalInstalacion',
        ),
    ]
