# Generated by Django 5.2.8 on 2025-11-27 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, verbose_name='Código postal')),
                ('estado_cliente', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado')], default='activo', max_length=20, verbose_name='Estado del cliente')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['nombre'], name='clientes_cl_nombre_c231de_idx'), models.Index(fields=['telefono'], name='clientes_cl_telefon_6177bc_idx'), models.Index(fields=['estado_cliente'], name='clientes_cl_estado__687b4e_idx')],
            },
        ),
    ]
