# Generated by Django 5.2.8 on 2025-11-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_cl_nombre_c231de_idx',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido1',
            field=models.CharField(default='', max_length=50, verbose_name='Primer apellido'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nombre', 'apellido1'], name='clientes_cl_nombre_8ec46d_idx'),
        ),
    ]
