# Generated by Django 5.2.8 on 2025-11-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_migrate_nombre_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido1',
            field=models.CharField(max_length=50, verbose_name='Primer apellido'),
        ),
    ]
