# Generated by Django 5.2.8 on 2026-01-05 16:24

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_historicalcliente_cliente_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cliente',
            name='unique_email_when_not_null',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, help_text='El correo electrónico debe ser único (si se proporciona)', max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(help_text='El teléfono debe ser único', max_length=15, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='email',
            field=models.EmailField(blank=True, help_text='El correo electrónico debe ser único (si se proporciona)', max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='telefono',
            field=models.CharField(help_text='El teléfono debe ser único', max_length=15, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), ('is_deleted', False)), fields=('email',), name='unique_email_when_not_null_and_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('telefono',), name='unique_telefono_when_not_deleted'),
        ),
    ]
