# Generated by Django 5.2.8 on 2026-01-05 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_renombrar_fecha_registro_a_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['apellido1', 'apellido2', 'nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RemoveConstraint(
            model_name='cliente',
            name='unique_email_when_not_null_and_not_deleted',
        ),
        migrations.RemoveConstraint(
            model_name='cliente',
            name='unique_telefono_when_not_deleted',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_cl_telefon_6177bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_cl_nombre_8ec46d_idx',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_cl_email_eae461_idx',
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='usuario',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Usuario que puede acceder al portal de cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Usuario que puede acceder al portal de cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='estado',
            field=models.CharField(max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['email', 'is_deleted'], name='clientes_cl_email_8671a7_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['telefono', 'is_deleted'], name='clientes_cl_telefon_9d074f_idx'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), ('is_deleted', False)), fields=('email',), name='unique_email_when_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('telefono__isnull', False)), fields=('telefono',), name='unique_telefono_when_not_deleted'),
        ),
    ]
