# Generated by Django 5.2.8 on 2026-01-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_agregar_debe_cambiar_password_historical'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud geográfica (obtenida automáticamente de la dirección)', max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud geográfica (obtenida automáticamente de la dirección)', max_digits=9, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud geográfica (obtenida automáticamente de la dirección)', max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud geográfica (obtenida automáticamente de la dirección)', max_digits=9, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='El correo electrónico debe ser único (si se proporciona)', max_length=254, null=True, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='El correo electrónico debe ser único (si se proporciona)', max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
    ]
