# Generated by Django 5.2.8 on 2026-01-19 18:56

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_agregar_email_unique_y_coordenadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcliente',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalcliente',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='historicalcliente',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcliente',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalcliente',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RemoveConstraint(
            model_name='cliente',
            name='unique_email_when_not_deleted',
        ),
        migrations.RemoveConstraint(
            model_name='cliente',
            name='unique_telefono_when_not_deleted',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_cl_is_dele_7bc56b_idx',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_cl_email_8671a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_cl_telefon_9d074f_idx',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='debe_cambiar_password',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de registro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, default=1, max_length=10, verbose_name='Código postal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nombre', 'apellido1'], name='clientes_cl_nombre_8ec46d_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['telefono'], name='clientes_cl_telefon_6177bc_idx'),
        ),
        migrations.DeleteModel(
            name='HistoricalCliente',
        ),
    ]
